### ISSUE TITLE
fatal error: EventToken.h: No such file or directory

### ISSUE THREAD

**Issue by simoole** [webview/webview_go#17]
#### gcc --version
gcc.exe (tdm64-1) 10.3.0

#### g++ --version
g++.exe (tdm64-1) 10.3.0

#### mingw32-make --version
GNU Make 3.82.90          
Built for i686-pc-mingw32
Copyright (C) 1988-2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by SteffenL** [comment]
Please see my answer in the following issue:

https://github.com/webview/webview/issues/1036
