### ISSUE TITLE
example appears as blank

### ISSUE THREAD

**Issue by quinn** [webview/webview_go#22]
when i run the example i get this:

![image](https://github.com/webview/webview_go/assets/3764/a52ec35a-b7b0-4174-9410-9a43e2964a79)

I can sort-of drag the text around and see it in the drag. can't really get a screenshot of that, but it shows the content is loading (and if i click in the right place, it increments). But nothing is visible.

**Comment by quinn** [comment]
I get the deprecation warning talked about elsewhere, and I also get this:

```
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 480x320: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 480x320: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 480x320: Permission denied
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
```

Another thing worth noting. `pkg-config` could not find gtk, so I had to add this env var:

```
PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig
```

For some reason packages got installed into `/usr/lib/x86_64-linux-gnu/pkgconfig` which my pkg-config isn't checking. I'm do for a reformat/reinstall, so this could be a me problem

**Comment by SteffenL** [comment]
Thanks for the report. I'll close this because it appears to be the same issue as reported here: https://github.com/webview/webview/issues/1055

If it's the same issue then it would be great if you could add some details about your system.
