### ISSUE TITLE
not able to use go run

### ISSUE THREAD

**Issue by benitogf** [webview/webview_go#29]
I updated and now using `go run` fails:
```
# command-line-arguments
/usr/local/go/pkg/tool/linux_amd64/link: running g++ failed: exit status 1
/usr/bin/ld: /tmp/go-link-598592747/000003.o: undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

using go build and then running the binary still works tho

**Comment by SteffenL** [comment]
It looks like we need to link the `ld` library but I don't get this error on my end.

Can you please share the following?

* Operating system
* Compiler version (`gcc --version`)
* Go version (`go version`)

**Comment by benitogf** [comment]
OS (ubuntu on WSL)
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

g++
```
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
```

go
```
go version go1.21.6 linux/amd64
```

**Comment by SteffenL** [comment]
I can reproduce this on a real Ubuntu installation with the same versions of software.

**Comment by SteffenL** [comment]
The fix works on my system so please check yours.

**Comment by benitogf** [comment]
yes that worked, thank you! 👏
