### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by GoHippo** [webview/webview_go#32]
os: windows 10
go: 1.22

I used to compile normally. An error is being thrown now:

CGO_ENABLED=0:
github.com/webview/webview_goback build restrictions exclude all Go files in C:\Users\root\go\pkg\mod\git
hub.com\webview\webview_go@v0.0.0-20240220051247-56f456ca3a43

CGO_ENABLED=1:
|# github.com/webview/webview_go
In the file included from C:/Users/root/go/pkg/mod/github.com/webview/webview_go@v0.0.0-20240220051247-56
f456ca3a43/libs/webview/include/webview.h:2076,
from webview.cc:1:
C:/Users/root/go/pkg/mod/github.com/webview/webview_go@v0.0.0-20240220051247-56f456ca3a43/libs/mswebv
iew2/include/WebView 2.h:978:10: fatal error: The event token.h: There is no such file or directory
978 | #include "EventToken.h"
| ^~~~~~~~~~~~~~
compilation is complete.

**Comment by SteffenL** [comment]
Issues related to `EventToken.h` have been answered before. You need a C++ toolchain that includes `EventToken.h` unless you provide the file by yourself.

https://github.com/webview/webview_go/issues?q=EventToken+is%3Aclosed
