### ISSUE TITLE
[bug] After launching the window, the methods ( "Navigation", "SetHtml") do not work

### ISSUE THREAD

**Issue by GoHippo** [webview/webview_go#7]
I needed to change the page address or apply html code, but after launching the main window, these methods ( "Navigation", "setHtml") no longer work. Nothing happens after they are called.
`	

	w := webview.New(false)
	defer w.Destroy()
	
	w.SetSize(800, 600, webview.HintNone)
	w.Navigate("https://example.com")

	go func() {
		for {
			w.Navigate("https://google.com")

			time.Sleep(5 * time.Second)
		}
	}()

	w.Run()
`

system_os: Windows 10
go_version: 1.19

**Comment by SteffenL** [comment]
You need to use `Dispatch()`:
```
w.Dispatch(func() {
	w.Navigate("https://google.com")
})
```

**Comment by SteffenL** [comment]
If you have anything to add then feel free to comment. Closing for now.
