### ISSUE TITLE
Error In webview.h

### ISSUE THREAD

**Issue by Fgaoxing** [webview/webview_go#8]
![image](https://github.com/webview/webview_go/assets/92655031/329cbd31-1a1b-429a-9bbc-b0fd7bee4212)

**Comment by SteffenL** [comment]
Your C/C++ toolchain (MinGW?) is missing the `EventToken.h` header.

**Comment by Fgaoxing** [comment]
So,what can I do？

**Comment by SteffenL** [comment]
You need to use a more modern MinGW distribution that has the header file. We have some suggestions in the readme file of the core library's repository:

https://github.com/webview/webview#mingw-w64-requirements

**Comment by Fgaoxing** [comment]
OK，thanks
